### PR TITLE
Update popupmenu class code example

### PR DESCRIPTION
**Pull request by Cabji**
1. Created new code example for popupmenu class
2. Remove old example as it didn't execute in script tester and even after modification didn't seem to do anything associated with popupmenu class, also used MDI which was removed from KVIrc.
3. Added return value note for $insertItem function

### CODE REVIEW

**Comment by roboirc** [comment]
Your code examples are not formatted properly. You should not remove the <br> tags as it means new line character in html. I am formatting your examples and updating the popupmenu class again.

**Comment by roboirc** [comment]
"< br >" tags mean new line in HTML.

**Comment by roboirc** [comment]
I fixed it and updated the git.

**Comment by Cabji** [comment]
< pre > tags render the text in preformatted layout, so < br > tags shouldn't be needed. the css styling that the kvirc docs had for pre was making the text not line break.

i believe it was this: pre { 	white-space: normal; }
in the head -> style tag that makes the preformatted text not line break.

see: https://www.w3schools.com/cssref/tryit.asp?filename=trycss_text_white-space for details

**Pull request merged**
